version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  pretty:
    format: '%(levelname)s: %(message)s'
handlers:
  console:
    formatter: pretty
    class: logging.StreamHandler
    stream: ext://sys.stderr
  file:
    formatter: default
    class: logging.FileHandler
    filename: server.log
loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: no
root:
  level: DEBUG
  handlers:
    - console
    - file
  propagate: no